/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcular.h"

int *
add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Requisicao de Adicao para %d e %d",argp->x, argp->y);
	result = argp-> x + argp-> y;
	return &result;
}

int *
sub_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Requisicao de Subtracao para %d e %d",argp->x, argp->y);
	result = argp-> x - argp-> y;
	return &result;
}

int *
mult_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Requisicao de Multiplicacao para %d e %d",argp->x, argp->y);
	result = argp-> x * argp-> y;
	return &result;
}
