/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcular.h"



int add( CLIENT *clnt, int x, int y) {
	operandos ops;
	int *result;

	ops.x = x;
	ops.y = y;

	result = add_100(&ops,clnt);
	if (result==NULL) {
		fprintf(stderr,"Problema na chamada RPC\n");
		exit(0);
	 }
	return(*result);
} 


int sub( CLIENT *clnt, int x, int y) {
	operandos ops;
	int *result;

	ops.x = x;
	ops.y = y;

	result = sub_100(&ops,clnt);
	if (result==NULL) {
		fprintf(stderr,"problema na chamada rpc\n");
		exit(0);
	 }
	return(*result);
} 


int mult( CLIENT *clnt, int x, int y) {
	operandos ops;
	int *result;

	ops.x = x;
	ops.y = y;

	result = mult_100(&ops,clnt);
	if (result==NULL) {
		fprintf(stderr,"problema na chamada rpc\n");
		exit(0);
	 }
	return(*result);
} 







int
main (int argc, char *argv[])
{
	CLIENT * clnt;
	int x,y;

	if(argc != 4)
	{
		printf("Params: %s  num1 num2 ",argv[0]);
		exit(0);
	}	
	
	clnt = clnt_create(argv[1], PROG, VERSAO, "udp");

	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1); 
	}

	x = atoi(argv[2]);
	y = atoi(argv[3]);
	printf("%d + %d = %d\n",x,y, add(clnt,x,y));
	printf("%d - %d = %d\n",x,y, sub(clnt,x,y));
	printf("%d * %d = %d\n",x,y, mult(clnt,x,y));
	return 0;
}
